language: haskell
branches:
  only:
  - source
env:
  global:
  - secure: h2220Jyqf/vh6va/X3PyAHb5GvPxcom/8LSq5UMJEqICtWR/jrbepItzP+esxunT/jHcz5LkoX/0BrSQV1e07uziDfeeV/NbWdi37PcwL7yvYkmPeY+mMfIqDAVIgrECVN2inafEpokCS2elhQjQZjAGkLWYbqOhXZNv5h9VO1Y=
ghc:
- 7.6
install:
- wget http://JoeyEremondi.github.io/Hakyll-executable/site.bin
- chmod +x ./site.bin
before_script:
- cd _site
- git checkout master
- git pull
- cd ..
script: ./site.bin build
after_script:
- cd _site
- git status
- git config --global user.email "joey@eremondi.com"
- git config --global user.name "JoeyEremondi"
- git add --all
- git commit -m "snapshot $(date '+%m/%d/%y %H:%M')"
- echo "$PAGES_URL" | tail -c 10
- git push "$PAGES_URL" master | grep -v http
- cd ..
