language: haskell
branches:
  only:
    - source
env:
  global:
   - secure: "FfF98Hf9xwiyUvNNIipROY6NurVNMOw3M1K0jGnQQT7IHbbId+dnDnHq5CG0EFWLiPo6GfP//7zAAEIE7YEOPY6d7FiIHhhplL+RFL7pUIISfzvUW4aN4LEnMnX0PhImiJ/o93eD8wa/IifJK8VBrEYPldYYSuOZk70UVQdLW2I="

ghc:
  - 7.6
install:
  - wget http://JoeyEremondi.github.io/Hakyll-executable/site.bin
  - chmod +x ./site.bin
before_script:
  - cd _site
  - git checkout master
  - git pull #origin master
  - cd ..
script: ./site.bin rebuild
after_script:
  - cd _site
  - git status
  - git add ./*
  - git config --global user.email "joey@eremondi.com"
  - git config --global user.name "JoeyEremondi"
  - git commit -m "snapshot $(date '+%m/%d/%y %H:%M')"
  - git push "$PAGES_URL" master 2>&1 | grep -v http
  - cd ..
